### ISSUE TITLE
Licensing of code

### ISSUE THREAD

**Issue by arthurp** [scalamacros/macrology201#1]
I would like to use a modified version of the owner splicing code in a 3-clause BSD project I am working on. 

Specifically I would like to use this code:
https://github.com/scalamacros/macrology201/blob/722854c9504e65e45663597c9b6baf93dca7d87f/macros/src/main/scala/Macros.scala

@xeno-by Would you be willing to make a license statement with respect to this repo and all it's past commits?

That way I can decide if the licenses are compatible and if I can use the code.

Thanks!

BTW, the code already appears in another project under a 3-clause PSD with a citation of course: https://github.com/pfn/iota/blob/master/macros/src/main/scala/iota/module/macros/Splicer.scala

**Comment by xeno-by** [comment]
Done: https://github.com/scalamacros/macrology201/blob/master/LICENSE.md. What do you think?

**Comment by arthurp** [comment]
I think this is just fine. Just for clarity, I would love to see a statement that all revisions of the repo are covered by this licence (in the README or LICENCE files), not just the revisions in which the licence appears. But I'm just nitpicking at this point.

Thanks.

**Comment by xeno-by** [comment]
Hmm I'm not really sure how we should approach this. @fommil, could you consult us please?

**Comment by fommil** [comment]
If you're copying and pasting some code, you only need to know the license at the point you copied it. Don't forget to include Eugene's LICENSE file in is entirety into your project at both source and runtime distribution, as is required by the modified BSD. I find putting it into the resources directory does the trick.

**Comment by arthurp** [comment]
Yep. I will get the licence properly included. We have a whole lot of them in there already.

The issue is that the LICENCE did not appear in the repo at the commit I copied from. This is in large part because this repo is actually used by looking at the history not the final commit. This is what complicates things.

But like I said: I don't think this is a big deal.

**Comment by fommil** [comment]
I've been stung enough in the past to assume the worst if a license is not present. Luckily it worked out well this time :-)

**Comment by xeno-by** [comment]
Allright, I'll close the issue then. Please let me know if you'd like me to do something in the future.
